### ISSUE TITLE
Can not save OP information

### ISSUE THREAD

**Issue by mainwindow** [GlowstonePlusPlus/GlowstonePlusPlus#104]
Error reading from: config\ops.json
 java.lang.NullPointerException
 at net.glowstone.util.bans.JsonListFile.load(JsonListFile.java:52)
 at net.glowstone.GlowServer.start(GlowServer.java:464)
 at net.glowstone.GlowServer.main(GlowServer.java:121)

What...:(...
I use Dragonet.

**Comment by mainwindow** [comment]
And after the server "op" command input, the server will get stuck for a few seconds...

**Comment by mastercoms** [comment]
What is the content of your ops.json?

**Comment by mastercoms** [comment]
I saw the contents on your other issue. Just delete ops.json and start the server again and op yourself.

**Comment by mainwindow** [comment]
YES, I tried, but when restart the server, the problem is always here.

**Comment by mastercoms** [comment]
What command do you use for restarting the server?

Are you in offline mode?

**Comment by mainwindow** [comment]
I using "stop" to shut down the server, and yes, in offline mode.

**Comment by mastercoms** [comment]
Sorry, but Glowstone++ does not support offline mode properly, and we can't provide help for servers in offline mode.

Of course, Glowstone++ will better support offline mode in the future, but we can never provide help to people who use it.
