### ISSUE TITLE
The Glowstone Test Server

### ISSUE THREAD

**Issue by mastercoms** [GlowstonePlusPlus/GlowstonePlusPlus#42]
Hi, I have a temp server we could use. I can't keep it forever, but for now we can use it.

Server address: therealms.us

Automatically updates when master builds successfully. It does not save the world, just kills the process.

**Comment by mastercoms** [comment]
@jimmikaelkael You are now op!

**Comment by jimmikaelkael** [comment]
It seems no, it might be because I joined the server before you've put it in offline mode. I suggest we keep online mode for now to keep our skin and prevent usurpation.

**Comment by mastercoms** [comment]
Ok.
