### ISSUE TITLE
Sponge only affects water once

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstonePlusPlus/GlowstonePlusPlus#90]
After placing the sponge in water, water flew back.

**Comment by mastercoms** [comment]
It seems like water does not check for this.

**Comment by DefinitlyEvil** [comment]
;)

**Comment by mastercoms** [comment]
I tested this, and this happens in vanilla minecraft too.

**Comment by DefinitlyEvil** [comment]
@mastercoms That's weird, I remember that placing a sponge will cause water not flowing to it. xD

**Comment by mastercoms** [comment]
This was changed in 1.8 I think, where sponges turn into wet sponges as soon as they absorb any water, and wet sponges cannot absorb water.

**Comment by DefinitlyEvil** [comment]
@mastercoms Cool!
